trigger:
  - main

extends:
  template: azure-pipelines.yml
  parameters:
    environmentName: PROD
    imageRepository: azure-pipeline-enhancement/prod
    dockerRegistryServiceConnection: prod-acr-service-connection
